from typing import Counter, Text
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QVBoxLayout, QAction
from db_test import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Приложение профориентирования")
        MainWindow.resize(552, 419)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_proforient = QtWidgets.QLabel(self.centralwidget)
        self.label_proforient.setGeometry(QtCore.QRect(213, 65, 141, 20))
        self.label_proforient.setObjectName("label_proforient")
        self.label_sruct_intel = QtWidgets.QLabel(self.centralwidget)
        self.label_sruct_intel.setGeometry(QtCore.QRect(39, 65, 121, 20))
        self.label_sruct_intel.setObjectName("label_sruct_intel")
        self.label_type_lich = QtWidgets.QLabel(self.centralwidget)
        self.label_type_lich.setGeometry(QtCore.QRect(423, 65, 81, 20))
        self.label_type_lich.setObjectName("label_type_lich")
        self.pushButton_ayzenk = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ayzenk.setGeometry(QtCore.QRect(27, 95, 130, 40))
        self.pushButton_ayzenk.setObjectName("pushButton_ayzenk")
        self.pushButton_holland = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_holland.setGeometry(QtCore.QRect(211, 95, 130, 40))
        self.pushButton_holland.setObjectName("pushButton_holland")
        self.pushButton_tomas_kliman = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_tomas_kliman.setGeometry(QtCore.QRect(395, 95, 130, 40))
        self.pushButton_tomas_kliman.setObjectName("pushButton_tomas_kliman")
        self.pushButton_kettel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_kettel.setGeometry(QtCore.QRect(27, 145, 130, 40))
        self.pushButton_kettel.setObjectName("pushButton_kettel")
        self.pushButton_unga = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_unga.setGeometry(QtCore.QRect(395, 145, 130, 40))
        self.pushButton_unga.setObjectName("pushButton_unga")
        self.pushButton_klimov = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_klimov.setGeometry(QtCore.QRect(211, 145, 130, 40))
        self.pushButton_klimov.setObjectName("pushButton_klimov")
        self.pushButton_ryzapkina = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ryzapkina.setGeometry(QtCore.QRect(211, 195, 130, 40))
        self.pushButton_ryzapkina.setObjectName("pushButton_ryzapkina")
        self.pushButton_brigs_mayers = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_brigs_mayers.setGeometry(QtCore.QRect(395, 195, 130, 40))
        self.pushButton_brigs_mayers.setObjectName("pushButton_brigs_mayers")
        self.pushButton_veksler = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_veksler.setGeometry(QtCore.QRect(27, 195, 130, 40))
        self.pushButton_veksler.setObjectName("pushButton_veksler")
        self.label_Type_test = QtWidgets.QLabel(self.centralwidget)
        self.label_Type_test.setGeometry(QtCore.QRect(171, 15, 211, 27))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_Type_test.setFont(font)
        self.label_Type_test.setObjectName("label_Type_test")
        self.pushButton_block_intell = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_block_intell.setGeometry(QtCore.QRect(26, 300, 130, 40))
        self.pushButton_block_intell.setObjectName("pushButton_block_intell")
        self.pushButton_block_lich = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_block_lich.setGeometry(QtCore.QRect(394, 300, 130, 40))
        self.pushButton_block_lich.setObjectName("pushButton_block_lich")
        self.pushButton_block_proforient = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_block_proforient.setGeometry(QtCore.QRect(210, 300, 130, 40))
        self.pushButton_block_proforient.setObjectName("pushButton_block_proforient")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(171, 250, 211, 27))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_result.setFont(font)
        self.label_result.setTextFormat(QtCore.Qt.PlainText)
        self.label_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_result.setObjectName("label_result")
        self.pushButton_all_result = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_all_result.setGeometry(QtCore.QRect(26, 350, 499, 40))
        self.pushButton_all_result.setObjectName("pushButton_all_result")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        quit = QAction("Close", MainWindow)
        quit.triggered.connect(MainWindow.closeEvent)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Система профориентации"))
        self.label_proforient.setText(_translate("MainWindow", "Профориентированность"))
        self.label_sruct_intel.setText(_translate("MainWindow", "Структура интелекта"))
        self.label_type_lich.setText(_translate("MainWindow", "Тип личности"))
        self.pushButton_ayzenk.setText(_translate("MainWindow", "Айзенк"))
        self.pushButton_holland.setText(_translate("MainWindow", "Дж. Голонда"))
        self.pushButton_tomas_kliman.setText(_translate("MainWindow", "Томас-Килманн"))
        self.pushButton_kettel.setText(_translate("MainWindow", "Кеттелл"))
        self.pushButton_unga.setText(_translate("MainWindow", "Юнга"))
        self.pushButton_klimov.setText(_translate("MainWindow", "Е. А. Климова"))
        self.pushButton_ryzapkina.setText(_translate("MainWindow", "Г. В. Рязапкина "))
        self.pushButton_brigs_mayers.setText(_translate("MainWindow", "Бриггс-Майерс"))
        self.pushButton_veksler.setText(_translate("MainWindow", "Векслер"))
        self.label_Type_test.setText(_translate("MainWindow", "Типы тестирования:"))
        self.pushButton_block_intell.setText(_translate("MainWindow", "Блок интелекта"))
        self.pushButton_block_lich.setText(_translate("MainWindow", "Блок личности"))
        self.pushButton_block_proforient.setText(_translate("MainWindow", "Блок профориент."))
        self.label_result.setText(_translate("MainWindow", "Результаты:"))
        self.pushButton_all_result.setText(_translate("MainWindow", "Обобщенный результат"))

    def err_msg(self):
        error = QMessageBox()
        error.setWindowTitle("Ошибка")
        error.setText("Выолните хотя бы один тест в данном блоке")
        error.setIcon(QMessageBox.Warning)
        error.setStandardButtons(QMessageBox.Ok)
        error.exec_()
        return (-1)

    def err_msg_all(self):
        error = QMessageBox()
        error.setWindowTitle("Ошибка")
        error.setText("Выолните хотя бы один тест в каждом блоке")
        error.setIcon(QMessageBox.Warning)
        error.setStandardButtons(QMessageBox.Ok)
        error.exec_()
        return (-1)

    def closeEvent(self, event):
        print("X is clicked")